#ifndef SMARTKEY_H
#define SMARTKEY_H

enum {GO_MODE0 = 256, GO_MODE1, GO_MODE2, GO_MODE3,
HISTORY_UP, HISTORY_DOWN, CURSOR_LEFT, CURSOR_RIGHT, GET_DICT, SHOW_KEYBOARD, COMPLETE,
MARKER_UP, MARKER_DOWN, MARKER_WORDLEFT, MARKER_WORDRIGHT, MARKER_INSERT, MARKER_INSERTBACK, MARKER_DICT, MARKER_DICTBACK,
GET_DICT0, GET_DICT1, GET_DICT2, GET_DICT3,
};

#endif
